apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: bankapp
spec:
  selector:
    matchLabels:
      app: bankapp
      replicas: 1
      strategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: pavanputtur/bankapp:1.0
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
 type: NodePort
  selector:
    app: bankapp
  ports:
  - name: http
  protocol: TCP
  nodePort: 31000
  port: 80
  targetPort: 8082
